version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    versioning-strategy: 'increase'
    ignore:
      - dependency-name: 'alert'
    open-pull-requests-limit: 0
